/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego;

/**
 *
 * @author Juancho
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Runnable{

    Jugador jugador = new Jugador();
    Logica logica = new Logica(jugador);
    private Thread hiloDibujo;
    
    public VentanaPrincipal() {
        
        initComponents();
        hiloDibujo = new Thread(this);
        hiloDibujo.start();
    }
    @Override
    public void run (){
        while (true){
        this.lblcarne.setText("Carne: "+this.jugador.getCarne());
        this.lblmadera.setText("Madera: "+this.jugador.getMadera());
        this.lblmetal.setText("Metal: "+this.jugador.getMetal());
        this.lblcazador.setText("Cazador: "+this.jugador.getCazador());
        this.lblleñador.setText("Leñador: "+this.jugador.getLeñador());
        this.lblminero.setText("Minero: "+this.jugador.getMinero());
        }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblaldeanos = new javax.swing.JLabel();
        lblcarne = new javax.swing.JLabel();
        lblmetal = new javax.swing.JLabel();
        lblmadera = new javax.swing.JLabel();
        lblrecursos = new javax.swing.JLabel();
        lblleñador = new javax.swing.JLabel();
        lblminero = new javax.swing.JLabel();
        lblcazador = new javax.swing.JLabel();
        btncazador = new javax.swing.JButton();
        btnleñador = new javax.swing.JButton();
        btnminero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblaldeanos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblaldeanos.setText("Aldeanos:");
        getContentPane().add(lblaldeanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblcarne.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblcarne.setText("Carne:");
        getContentPane().add(lblcarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        lblmetal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblmetal.setText("Metal:");
        getContentPane().add(lblmetal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        lblmadera.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblmadera.setText("Madera: ");
        getContentPane().add(lblmadera, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblrecursos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblrecursos.setText("Recursos: ");
        getContentPane().add(lblrecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblleñador.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblleñador.setText("Leñador:");
        getContentPane().add(lblleñador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblminero.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblminero.setText("Minero:");
        getContentPane().add(lblminero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        lblcazador.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblcazador.setText("Cazador:");
        getContentPane().add(lblcazador, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        btncazador.setText("crear");
        btncazador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncazadorActionPerformed(evt);
            }
        });
        getContentPane().add(btncazador, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, -1, -1));

        btnleñador.setText("crear");
        btnleñador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleñadorActionPerformed(evt);
            }
        });
        getContentPane().add(btnleñador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btnminero.setText("crear");
        btnminero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmineroActionPerformed(evt);
            }
        });
        getContentPane().add(btnminero, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnleñadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleñadorActionPerformed
       logica.crearAldeano(1);
    }//GEN-LAST:event_btnleñadorActionPerformed

    private void btnmineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmineroActionPerformed
        logica.crearAldeano(2);
    }//GEN-LAST:event_btnmineroActionPerformed

    private void btncazadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncazadorActionPerformed
         logica.crearAldeano(3);
    }//GEN-LAST:event_btncazadorActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncazador;
    private javax.swing.JButton btnleñador;
    private javax.swing.JButton btnminero;
    private javax.swing.JLabel lblaldeanos;
    private javax.swing.JLabel lblcarne;
    private javax.swing.JLabel lblcazador;
    private javax.swing.JLabel lblleñador;
    private javax.swing.JLabel lblmadera;
    private javax.swing.JLabel lblmetal;
    private javax.swing.JLabel lblminero;
    private javax.swing.JLabel lblrecursos;
    // End of variables declaration//GEN-END:variables
}
